% Compute a visual word vocabulary

setup ;

% from training images
names{1} = textread('data/background_train.txt','%s') ;
names{2} = textread('data/airplanes_train.txt','%s') ;
names{3} = textread('data/Leopards_train.txt','%s') ;
names{4} = textread('data/umbrella_train.txt','%s') ;
names{5} = textread('data/accordion_train.txt','%s') ;
names{6} = textread('data/bass_train.txt','%s') ;
names{7} = textread('data/brain_train.txt','%s') ;
names{8} = textread('data/buddha_train.txt','%s') ;
names{9} = textread('data/butterfly_train.txt','%s') ;
names{10} = textread('data/camera_train.txt','%s') ;
names{11} = textread('data/car_side_train.txt','%s') ;
names{12} = textread('data/chair_train.txt','%s') ;
names{13} = textread('data/chandelier_train.txt','%s') ;
names{14} = textread('data/cougar_face_train.txt','%s') ;
names{15} = textread('data/crab_train.txt','%s') ;
names{16} = textread('data/crocodile_head_train.txt','%s') ;
names{17} = textread('data/cup_train.txt','%s') ;
names{18} = textread('data/dolphin_train.txt','%s') ;
names{19} = textread('data/dragonfly_train.txt','%s') ;
names{20} = textread('data/electric_guitar_train.txt','%s') ;
names{21} = textread('data/euphonium_train.txt','%s') ;
names{22} = textread('data/ewer_train.txt','%s') ;
names{23} = textread('data/Faces_easy_train.txt','%s') ;
names{24} = textread('data/flamingo_train.txt','%s') ;
names{25} = textread('data/gramophone_train.txt','%s') ;
names{26} = textread('data/grand_piano_train.txt','%s') ;
names{27} = textread('data/hawksbill_train.txt','%s') ;
names{28} = textread('data/helicopter_train.txt','%s') ;
names{29} = textread('data/ibis_train.txt','%s') ;
names{30} = textread('data/kangaroo_train.txt','%s') ;
names{31} = textread('data/lamp_train.txt','%s') ;
names{32} = textread('data/laptop_train.txt','%s') ;
names{33} = textread('data/lotus_train.txt','%s') ;
names{34} = textread('data/minaret_train.txt','%s') ;
names{35} = textread('data/Motorbikes_train.txt','%s') ;
names{36} = textread('data/nautilus_train.txt','%s') ;
names{37} = textread('data/pyramid_train.txt','%s') ;
names{38} = textread('data/revolver_train.txt','%s') ;
names{39} = textread('data/rhino_train.txt','%s') ;
names{40} = textread('data/scorpion_train.txt','%s') ;
names{41} = textread('data/soccer_ball_train.txt','%s') ;
names{42} = textread('data/starfish_train.txt','%s') ;
names{43} = textread('data/stop_sign_train.txt','%s') ;
names{44} = textread('data/sunflower_train.txt','%s') ;
names{45} = textread('data/watch_train.txt','%s') ;
names{46} = textread('data/wheelchair_train.txt','%s') ;
names{47} = textread('data/windsor_chair_train.txt','%s') ;
names{48} = textread('data/yin_yang_train.txt','%s') ;
names{49} = textread('data/dalmatian_train.txt','%s') ;
names{50} = textread('data/elephant_train.txt','%s') ;


names = cat(1,names{:})' ;
if ~exist('data/vocabulary.mat')
  vocabulary = computeVocabularyFromImageList(vl_colsubset(names,200,'uniform')) ;
  %save('data/vocabulary.mat', '-STRUCT', 'vocabulary') ;
  save data/vocabulary.mat vocabulary
else
  vocabulary = load('data/vocabulary.mat') ;
end

% --------------------------------------------------------------------
%                                                   Compute histograms
% --------------------------------------------------------------------

for subset = {'background_train', ...
              'background_val', ...
              'airplanes_train', ...
              'airplanes_val', ...
              'Leopards_train', ...
              'Leopards_val', ...
              'accordion_train', ...
              'accordion_val', ...
              'bass_train', ...
              'bass_val', ...
              'brain_train', ...
              'brain_val', ...
              'buddha_train', ...
              'buddha_val', ...
              'butterfly_train', ...
              'butterfly_val', ...
              'car_side_train', ...
              'car_side_val', ...
              'chair_train', ...
              'chair_val', ...
              'chandelier_train', ...
              'chandelier_val', ...
              'cougar_face_train', ...
              'cougar_face_val', ...
              'crab_train', ...
              'crab_val', ...
              'crocodile_head_train', ...
              'crocodile_head_val', ...
              'cup_train', ...
              'cup_val', ...
              'dalmatian_train', ...
              'dalmatian_val', ...
              'dolphin_train', ...
              'dolphin_val', ...
              'dragonfly_train', ...
              'dragonfly_val', ...
              'electric_guitar_train', ...
              'electric_guitar_val', ...
              'elephant_train', ...
              'elephant_val', ...
              'euphonium_train', ...
              'euphonium_val', ...
              'ewer_train', ...
              'ewer_val', ...
              'Faces_easy_train', ...
              'Faces_easy_val', ...
              'flamingo_train', ...
              'flamingo_val', ...
              'gramophone_train', ...
              'gramophone_val', ...
              'grand_piano_train', ...
              'grand_piano_val', ...
              'hawksbill_train', ...
              'hawksbill_val', ...
              'helicopter_train', ...
              'helicopter_val', ...
              'ibis_train', ...
              'ibis_val', ...
              'kangaroo_train', ...
              'kangaroo_val', ...
              'lamp_train', ...
              'lamp_val', ...
              'laptop_train', ...
              'laptop_val', ...
              'lotus_train', ...
              'lotus_val', ...
              'minaret_train', ...
              'minaret_val', ...
              'Motorbikes_train', ...
              'Motorbikes_val', ...
              'nautilus_train', ...
              'nautilus_val', ...
              'pyramid_train', ...
              'pyramid_val', ...
              'revolver_train', ...
              'revolver_val', ...
              'rhino_train', ...
              'rhino_val', ...
              'scorpion_train', ...
              'scorpion_val', ...
              'soccer_ball_train', ...
              'soccer_ball_val', ...
              'starfish_train', ...
              'starfish_val', ...
              'stop_sign_train', ...
              'stop_sign_val', ...
              'sunflower_train', ...
              'sunflower_val', ...
              'watch_train', ...
              'watch_val', ...
              'wheelchair_train', ...
              'wheelchair_val', ...
              'windsor_chair_train', ...
              'windsor_chair_val', ...
              'yin_yang_train', ...
              'yin_yang_val', ...
              'umbrella_train', ...
              'umbrella_val'}

  fprintf('Processing %s\n', char(subset)) ;
  names = textread(fullfile('data', [char(subset) '.txt']), '%s') ;
  %names
  histograms = computeHistogramsFromImageList(vocabulary, names) ;
  save(fullfile('data',[char(subset) '_hist.mat']), 'names', 'histograms') ;
end
